# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admin(object):
    def setupUi(self, Admin):
        Admin.setObjectName("Admin")
        Admin.resize(850, 600)
        self.backButton = QtWidgets.QPushButton(Admin)
        self.backButton.setGeometry(QtCore.QRect(610, 490, 81, 31))
        self.backButton.setObjectName("backButton")
        self.resolveButton = QtWidgets.QPushButton(Admin)
        self.resolveButton.setGeometry(QtCore.QRect(160, 200, 240, 120))
        self.resolveButton.setObjectName("resolveButton")
        self.rankingButton = QtWidgets.QPushButton(Admin)
        self.rankingButton.setGeometry(QtCore.QRect(460, 200, 240, 120))
        self.rankingButton.setObjectName("rankingButton")
        self.label = QtWidgets.QLabel(Admin)
        self.label.setGeometry(QtCore.QRect(310, 70, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Admin)
        QtCore.QMetaObject.connectSlotsByName(Admin)

    def retranslateUi(self, Admin):
        _translate = QtCore.QCoreApplication.translate
        Admin.setWindowTitle(_translate("Admin", "Dialog"))
        self.backButton.setText(_translate("Admin", "Back"))
        self.resolveButton.setText(_translate("Admin", "Resolve"))
        self.rankingButton.setText(_translate("Admin", "Ranking"))
        self.label.setText(_translate("Admin", "Admin Panel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Admin = QtWidgets.QDialog()
    ui = Ui_Admin()
    ui.setupUi(Admin)
    Admin.show()
    sys.exit(app.exec_())
