# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contact.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ContactUsWindow(object):
    def setupUi(self, ContactUsWindow):
        ContactUsWindow.setObjectName("ContactUsWindow")
        ContactUsWindow.resize(850, 600)
        self.centralwidget = QtWidgets.QWidget(ContactUsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 81, 31))
        self.label.setStyleSheet("font-size:12pt; font-weight:600;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(660, 10, 161, 31))
        self.label_2.setStyleSheet("font-size:12pt; font-weight:600;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 70, 741, 161))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(330, 40, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(62)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font-size:10pt; font-weight:500;")
        self.label_4.setObjectName("label_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(50, 260, 750, 121))
        self.tabWidget.setWhatsThis("")
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 331, 71))
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 331, 71))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 331, 71))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 331, 71))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_3, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setEnabled(True)
        self.tabWidget_2.setGeometry(QtCore.QRect(50, 400, 750, 121))
        self.tabWidget_2.setWhatsThis("")
        self.tabWidget_2.setTabBarAutoHide(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_7 = QtWidgets.QLabel(self.tab_7)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 331, 71))
        self.label_7.setObjectName("label_7")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.label_8 = QtWidgets.QLabel(self.tab_8)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 331, 71))
        self.label_8.setObjectName("label_8")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.label_12 = QtWidgets.QLabel(self.tab_9)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 331, 71))
        self.label_12.setObjectName("label_12")
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.label_11 = QtWidgets.QLabel(self.tab_10)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 331, 71))
        self.label_11.setObjectName("label_11")
        self.tabWidget_2.addTab(self.tab_10, "")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(710, 540, 93, 30))
        self.pushButton.setStyleSheet("font-size:10pt; font-weight:500;")
        self.pushButton.setObjectName("pushButton")
        ContactUsWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ContactUsWindow)
        self.statusbar.setObjectName("statusbar")
        ContactUsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ContactUsWindow)
        self.tabWidget.setCurrentIndex(3)
        self.tabWidget_2.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(ContactUsWindow)
        ContactUsWindow.setTabOrder(self.tabWidget, self.tabWidget_2)

    def retranslateUi(self, ContactUsWindow):
        _translate = QtCore.QCoreApplication.translate
        ContactUsWindow.setWindowTitle(_translate("ContactUsWindow", "ContactUsWindow"))
        self.label.setText(_translate("ContactUsWindow", "Cypress"))
        self.label_2.setText(_translate("ContactUsWindow", "City of Toronto"))
        self.label_3.setText(_translate("ContactUsWindow", " City Hall \n"
" 100 Queen St. W. \n"
" Toronto, ON \n"
"\n"
" Office Hours: 9.00am - 6.00pm \n"
" Email us at: contactus@cypress.com \n"
"\n"
" (For reporting any of the following issues, call us at the respective given contact numbers. We are open 24/7)"))
        self.label_4.setText(_translate("ContactUsWindow", "Contact Information"))
        self.label_9.setText(_translate("ContactUsWindow", "Phone no.: 416-338-0889 \n"
" Fax: 416-338-0889 \n"
" Email: contactus@cypress.com \n"
" (For urgent matters, please call us. We are open 24/7)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ContactUsWindow", "Tree Collapse"))
        self.label_10.setText(_translate("ContactUsWindow", "Phone no.: 416-338-0888 \n"
" Fax: 416-338-0888 \n"
" Email: contactus@cypress.com \n"
" (For urgent matters, please call us. We are open 24/7)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("ContactUsWindow", "Flooded Streets"))
        self.label_5.setText(_translate("ContactUsWindow", "Phone no.: 416-338-0887 \n"
" Fax: 416-338-0887 \n"
" Email: contactus@cypress.com \n"
" (For urgent matters, please call us. We are open 24/7)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ContactUsWindow", "Mold and Spore Growth"))
        self.label_6.setText(_translate("ContactUsWindow", "Phone no.: 416-338-0886 \n"
" Fax: 416-338-0886 \n"
" Email: contactus@cypress.com \n"
" (For urgent matters, please call us. We are open 24/7)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ContactUsWindow", "Utility Failures"))
        self.label_7.setText(_translate("ContactUsWindow", "Phone no.: 416-338-0885 \n"
" Fax: 416-338-0885 \n"
" Email: contactus@cypress.com \n"
" (For urgent matters, please call us. We are open 24/7)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("ContactUsWindow", "Potholes"))
        self.label_8.setText(_translate("ContactUsWindow", "Phone no.: 416-338-0884 \n"
" Fax: 416-338-0884 \n"
" Email: contactus@cypress.com \n"
" (For urgent matters, please call us. We are open 24/7)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("ContactUsWindow", "City Property Vandalism"))
        self.label_12.setText(_translate("ContactUsWindow", "Phone no.: 416-338-0883 \n"
" Fax: 416-338-0883 \n"
" Email: contactus@cypress.com \n"
" (For urgent matters, please call us. We are open 24/7)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("ContactUsWindow", "Eroded Streets"))
        self.label_11.setText(_translate("ContactUsWindow", "Phone no.: 416-338-0882 \n"
" Fax: 416-338-0882 \n"
" Email: contactus@cypress.com \n"
" (For urgent matters, please call us. We are open 24/7)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("ContactUsWindow", "Garbage or Any Other Road Blocking Objects"))
        self.pushButton.setText(_translate("ContactUsWindow", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ContactUsWindow = QtWidgets.QMainWindow()
    ui = Ui_ContactUsWindow()
    ui.setupUi(ContactUsWindow)
    ContactUsWindow.show()
    sys.exit(app.exec_())
