# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deleteProfileFeedback.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deleteProfileFeedback(object):
    def setupUi(self, deleteProfileFeedback):
        deleteProfileFeedback.setObjectName("deleteProfileFeedback")
        deleteProfileFeedback.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(deleteProfileFeedback)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(deleteProfileFeedback)
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.label_2 = QtWidgets.QLabel(deleteProfileFeedback)
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(deleteProfileFeedback)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.label_4 = QtWidgets.QLabel(deleteProfileFeedback)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4, 0, QtCore.Qt.AlignBottom)
        self.lineEdit = QtWidgets.QLineEdit(deleteProfileFeedback)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label = QtWidgets.QLabel(deleteProfileFeedback)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignLeft)
        self.textEdit = QtWidgets.QTextEdit(deleteProfileFeedback)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(deleteProfileFeedback)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignRight)
        self.pushButton = QtWidgets.QPushButton(deleteProfileFeedback)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(deleteProfileFeedback)
        QtCore.QMetaObject.connectSlotsByName(deleteProfileFeedback)

    def retranslateUi(self, deleteProfileFeedback):
        _translate = QtCore.QCoreApplication.translate
        deleteProfileFeedback.setWindowTitle(_translate("deleteProfileFeedback", "Delete Profile"))
        self.label_3.setText(_translate("deleteProfileFeedback", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">City Of Toronto </span></p></body></html>"))
        self.label_2.setText(_translate("deleteProfileFeedback", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Cypress</span></p></body></html>"))
        self.label_4.setText(_translate("deleteProfileFeedback", "1. Secret question: What is your favourite colour? (Type in below to confirm this is your profile) "))
        self.label.setText(_translate("deleteProfileFeedback", "2. Please let us know why you are deleting your profile (to help improve our service):"))
        self.pushButton_2.setText(_translate("deleteProfileFeedback", "Submit and Delete Profile"))
        self.pushButton.setText(_translate("deleteProfileFeedback", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    deleteProfileFeedback = QtWidgets.QDialog()
    ui = Ui_deleteProfileFeedback()
    ui.setupUi(deleteProfileFeedback)
    deleteProfileFeedback.show()
    sys.exit(app.exec_())
