# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MainScreen(object):
    def setupUi(self, Cypress):
        Cypress.setObjectName("Cypress")
        Cypress.resize(850, 600)
        self.centralwidget = QtWidgets.QWidget(Cypress)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 60, 381, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 150, 241, 231))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Toronto.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 420, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 420, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        Cypress.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Cypress)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 26))
        self.menubar.setObjectName("menubar")
        Cypress.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Cypress)
        self.statusbar.setObjectName("statusbar")
        Cypress.setStatusBar(self.statusbar)

        self.retranslateUi(Cypress)
        QtCore.QMetaObject.connectSlotsByName(Cypress)

    def retranslateUi(self, Cypress):
        _translate = QtCore.QCoreApplication.translate
        Cypress.setWindowTitle(_translate("Cypress", "MainWindow"))
        self.label.setText(_translate("Cypress", "CYPRESS"))
        self.pushButton.setText(_translate("Cypress", "English"))
        self.pushButton_2.setText(_translate("Cypress", "French"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Cypress = QtWidgets.QMainWindow()
    ui = Ui_Cypress()
    ui.setupUi(Cypress)
    Cypress.show()
    sys.exit(app.exec_())
