# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notificationScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Notification(object):
    def setupUi(self, Notification):
        Notification.setObjectName("Notification")
        Notification.resize(850, 600)
        self.centralwidget = QtWidgets.QWidget(Notification)
        self.centralwidget.setObjectName("centralwidget")
        self.cityBox = QtWidgets.QCheckBox(self.centralwidget)
        self.cityBox.setGeometry(QtCore.QRect(320, 30, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cityBox.setFont(font)
        self.cityBox.setAutoExclusive(True)
        self.cityBox.setObjectName("cityBox")
        self.userBox = QtWidgets.QCheckBox(self.centralwidget)
        self.userBox.setGeometry(QtCore.QRect(320, 70, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.userBox.setFont(font)
        self.userBox.setAutoExclusive(True)
        self.userBox.setObjectName("userBox")
        self.textBox = QtWidgets.QTextEdit(self.centralwidget)
        self.textBox.setGeometry(QtCore.QRect(60, 170, 721, 261))
        self.textBox.setObjectName("textBox")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(60, 450, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sendButton.setFont(font)
        self.sendButton.setObjectName("sendButton")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(700, 450, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 30, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 110, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        Notification.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Notification)
        self.statusbar.setObjectName("statusbar")
        Notification.setStatusBar(self.statusbar)

        self.retranslateUi(Notification)
        QtCore.QMetaObject.connectSlotsByName(Notification)

    def retranslateUi(self, Notification):
        _translate = QtCore.QCoreApplication.translate
        Notification.setWindowTitle(_translate("Notification", "MainWindow"))
        self.cityBox.setText(_translate("Notification", "Send to city officials"))
        self.userBox.setText(_translate("Notification", "Send to users"))
        self.textBox.setHtml(_translate("Notification", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.sendButton.setText(_translate("Notification", "Send"))
        self.cancelButton.setText(_translate("Notification", "Cancel"))
        self.label.setText(_translate("Notification", "Select recipient:"))
        self.label_2.setText(_translate("Notification", "Message:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Notification = QtWidgets.QMainWindow()
    ui = Ui_Notification()
    ui.setupUi(Notification)
    Notification.show()
    sys.exit(app.exec_())
