# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rankingScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ranking(object):
    def setupUi(self, Ranking):
        Ranking.setObjectName("Ranking")
        Ranking.resize(850, 600)
        self.doneButton = QtWidgets.QPushButton(Ranking)
        self.doneButton.setGeometry(QtCore.QRect(350, 550, 151, 31))
        self.doneButton.setObjectName("doneButton")
        self.rankedList = QtWidgets.QTextBrowser(Ranking)
        self.rankedList.setGeometry(QtCore.QRect(30, 90, 380, 450))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rankedList.setFont(font)
        self.rankedList.setTabStopWidth(80)
        self.rankedList.setObjectName("rankedList")
        self.listLabel = QtWidgets.QLabel(Ranking)
        self.listLabel.setGeometry(QtCore.QRect(30, 10, 801, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.listLabel.setFont(font)
        self.listLabel.setObjectName("listLabel")
        self.addressList = QtWidgets.QTextBrowser(Ranking)
        self.addressList.setGeometry(QtCore.QRect(440, 90, 380, 450))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addressList.setFont(font)
        self.addressList.setTabStopWidth(80)
        self.addressList.setObjectName("addressList")

        self.retranslateUi(Ranking)
        QtCore.QMetaObject.connectSlotsByName(Ranking)

    def retranslateUi(self, Ranking):
        _translate = QtCore.QCoreApplication.translate
        Ranking.setWindowTitle(_translate("Ranking", "Dialog"))
        self.doneButton.setText(_translate("Ranking", "Done"))
        self.rankedList.setHtml(_translate("Ranking", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.listLabel.setText(_translate("Ranking", "Problems and Areas ranked from most reports to least:"))
        self.addressList.setHtml(_translate("Ranking", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ranking = QtWidgets.QDialog()
    ui = Ui_Ranking()
    ui.setupUi(Ranking)
    Ranking.show()
    sys.exit(app.exec_())
