import sys
from PyQt5 import QtWidgets, QtGui, QtCore
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QHBoxLayout, QPushButton
from PyQt5.QtGui import QPixmap, QIcon

class Ui_ReportingWindow(object):
    def setupUi(self, ReportingWindow):
        ReportingWindow.setObjectName("ReportingWindow")
        ReportingWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ReportingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 81, 31))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(630, 0, 161, 31))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(500, 350, 93, 28))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setObjectName("pushButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 30, 751, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(320, 180, 111, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(320, 220, 131, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(320, 260, 171, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(70, 180, 111, 20))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(70, 220, 95, 20))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_6.setGeometry(QtCore.QRect(70, 260, 171, 20))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_7.setGeometry(QtCore.QRect(70, 300, 111, 20))
        self.radioButton_7.setObjectName("radioButton_7")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(740, 560, 41, 31))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(60, 140, 671, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.radioButton_8 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_8.setGeometry(QtCore.QRect(320, 300, 291, 20))
        self.radioButton_8.setObjectName("radioButton_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 350, 93, 28))
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 120, 201, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 70, 81, 21))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(160, 70, 571, 22))
        self.lineEdit.setObjectName("lineEdit")
        #ReportingWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ReportingWindow)
        QtCore.QMetaObject.connectSlotsByName(ReportingWindow)

    def retranslateUi(self, ReportingWindow):
        _translate = QtCore.QCoreApplication.translate
        ReportingWindow.setWindowTitle(_translate("ReportingWindow", "ReportingWindow"))
        self.label.setText(_translate("ReportingWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Cypress</span></p></body></html>"))
        self.label_2.setText(_translate("ReportingWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">City Of Toronto</span></p></body></html>"))
        self.pushButton.setText(_translate("ReportingWindow", "Report"))
        self.radioButton.setText(_translate("ReportingWindow", "Tree Collapse"))
        self.radioButton_2.setText(_translate("ReportingWindow", "Flooded Streets"))
        self.radioButton_3.setText(_translate("ReportingWindow", "Mold and Spore Growth"))
        self.radioButton_4.setText(_translate("ReportingWindow", "Utility Failures"))
        self.radioButton_5.setText(_translate("ReportingWindow", "Potholes"))
        self.radioButton_6.setText(_translate("ReportingWindow", "City Property Vandalism"))
        self.radioButton_7.setText(_translate("ReportingWindow", "Eroded Streets"))
        self.label_7.setText(_translate("ReportingWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">FAQ</span></p></body></html>"))
        self.radioButton_8.setText(_translate("ReportingWindow", "Garbage or Any Other Road Blocking Objects"))
        self.pushButton_2.setText(_translate("ReportingWindow", "Cancel"))
        self.label_3.setText(_translate("ReportingWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Problem at the Site:</span></p><p><br/></p></body></html>"))
        self.label_4.setText(_translate("ReportingWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Address:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReportingWindow = QtWidgets.QMainWindow()
    ui = Ui_ReportingWindow()
    ui.setupUi(ReportingWindow)
    ReportingWindow.show()
    sys.exit(app.exec_())
