from PyQt5 import QtCore, QtGui, QtWidgets
from database import database

class RetrievePassword(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonRetrieve = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRetrieve.setGeometry(QtCore.QRect(210, 340, 151, 51))
        self.pushButtonRetrieve.setObjectName("pushButtonRetrieve")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 230, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 270, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEditUsername = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditUsername.setGeometry(QtCore.QRect(300, 220, 191, 31))
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.lineEditSecretQuestion = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSecretQuestion.setGeometry(QtCore.QRect(420, 270, 221, 31))
        self.lineEditSecretQuestion.setObjectName("lineEditSecretQuestion")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 150, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(400, 340, 151, 51))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonRetrieve.setText(_translate("MainWindow", "Retrieve Password"))
        self.label.setText(_translate("MainWindow", "Enter Username:"))
        self.label_2.setText(_translate("MainWindow", "What is your favourite colour?"))
        self.pushButton.setText(_translate("MainWindow", "Back to Login"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = RetrievePassword()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
