# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secretqPrompt1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_secretQPrompt(object):
    def setupUi(self, secretQPrompt):
        secretQPrompt.setObjectName("secretQPrompt")
        secretQPrompt.resize(400, 250)
        self.gridLayout = QtWidgets.QGridLayout(secretQPrompt)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(secretQPrompt)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(secretQPrompt)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(secretQPrompt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.pushButton = QtWidgets.QPushButton(secretQPrompt)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignBottom)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)

        self.retranslateUi(secretQPrompt)
        QtCore.QMetaObject.connectSlotsByName(secretQPrompt)

    def retranslateUi(self, secretQPrompt):
        _translate = QtCore.QCoreApplication.translate
        secretQPrompt.setWindowTitle(_translate("secretQPrompt", "Delete Profile"))
        self.label.setText(_translate("secretQPrompt", "Secret question: What is your favourite colour? (Please input a case-sensitive answer)"))
        self.pushButton_2.setText(_translate("secretQPrompt", "Enter"))
        self.pushButton.setText(_translate("secretQPrompt", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    secretQPrompt = QtWidgets.QDialog()
    ui = Ui_secretQPrompt()
    ui.setupUi(secretQPrompt)
    secretQPrompt.show()
    sys.exit(app.exec_())
